### ISSUE TITLE
Field Precision - Regarding Lines 1022-1029 within schema_fgdb_v2.py

### ISSUE THREAD

**Issue by NCT911-DLindsey** [NENA911/NG911GISDataModel#33]
Hey Tom and/or Jason,

I'm currently reviewing the RoadCenterline section within schema_fgdb_v2.py (lines 1022-1029 specifically).

Within the GIS Data Model, the field width is capped at 6 digits. However, the schema script does not have this limitation set. 

**FromAddr_L**, **ToAddr_L**, **FromAddr_R**, and **ToAddr_R** all have the index 2 position set as empty strings. Should this field precision value at Index 2 be "6" instead of an empty string?

Link to the lines of code:
https://github.com/NENA911/NG911GISDataModel/blob/986686da9ae68cdcadf9766cd5943f93969fbbf9/esri_geodatabase/NENA_NG911_Scripts/schema/schema_fgdb_v2.py#L1022-L1029

GIS Data Model specifications:
![image](https://user-images.githubusercontent.com/58236078/206031005-df20dbdf-0248-4fa0-a974-3ba0d4c4a9cd.png)

The current Index 2 values within the schema template for field precision:
![image](https://user-images.githubusercontent.com/58236078/206031339-0e06df4a-37d7-4590-b494-9ec4aa76031e.png)

Refresher on Field Precision (I won't lie, I had to look it up again...):
![image](https://user-images.githubusercontent.com/58236078/206032430-6dee3936-4377-4eb9-8138-6994374f230d.png)

Just double checking,

David L.

**Comment by NCT911-DLindsey** [comment]
Hey Tom, thanks for the explanation. I hadn't made it to the Domain section yet when I sent that (my apologies). 

However, now that you mention the domain constraints, I went in and did some testing with the Esri File GDB template in ArcMap. Turns out, those domain constraints are not being enforced (at least with 10.8.1). The domain constraints list the max value of 999999, but I was able to successfully add/save integer values up to 2,147,483,647 (long int max). It finally tossed an error at me when I exceeded that value. I'm unable to compare the behavior in PostgreSQL.

![image](https://user-images.githubusercontent.com/58236078/206510867-0a8da895-ebaa-451c-85d9-bd184341040d.png)

![image](https://user-images.githubusercontent.com/58236078/206505757-fc5d119a-f0a5-4900-acbd-27144fa0ce44.png)

**Comment by tomneer** [comment]
Thank you for the additional checks. It's always interesting finding the differences between ArcMap and ArcGIS Pro and agree that values should error instead of converting. Regarding rabbit holes, in ArcGIS Pro, this issue could be handled using [Constraint or Validation Rules](https://pro.arcgis.com/en/pro-app/latest/help/data/geodatabases/overview/constraint-attribute-rules.htm), which would provide a specific error code. However, Attribute Rules do not work with ArcMap.

One of our balancing acts will be determining how many "workarounds" are appropriate for vendor software issues versus just listing them under a **Known Issues** section. There is only so far back that we can support a software product that has been discontinued.

**Comment by jasonhorning** [comment]
I would consider this particular issue an Esri Bug.  Nothing, as far as I can tell, we're doing wrong but it should be reported to Esri.
