### ISSUE TITLE
SSAP - Elevation Field Type Issue

### ISSUE THREAD

**Issue by geofinne** [NENA911/NG911GISDataModel#46]
The data model standard lists the _Elevation_ field (in SiteStructureAddressPoints) as a width of 6, however the geodatabase uses a **short integer** field type that can only store up to a length of 5. Should we switch this to a **long integer**?

**Comment by tomneer** [comment]
Confirmed that the "Elevation" field in the geodatabase is storing "SHORT" not "LONG" integers.

**Comment by jasonhorning** [comment]
I remember considering this in V1. Since the type is "N – Non-negative integer" and we're highly unlikely to have any features with a height above ellipsoid of 32768 meters I think we just chose short for storage considerations (a minor thing).  I see what you're saying about the length (6) so I can make the change to LONG or we just refer it to V3 (asking them to decrease to 5) and stick with SHORT for now.  I'm OK either way.  The standard doesn't specify short or long, and I'm not sure they thought about how long a short is vs long when they set the length.  I'm almost wondering if it doesn't make sense to include a type that's capable of storing some decimal places vs an integer.

**Comment by geofinne** [comment]
Good point. I wonder why they didn't consider a type that would support decimal places.  I think it's worth a discussion, and as long as the templates are in sync with what the data model standard doc says then we are good.

**Comment by jasonhorning** [comment]
I show this issue has having had discussion in the WG and that the FGDB & PostgreSQL Tasks have been completed.  Can we close?

**Comment by tomneer** [comment]
The Elevation field was changed to a LONG integer type
